export const MODULES = [
  {
    id: 'fundamental-rights',
    title: 'Fundamental Rights',
    description: 'Explore the core rights guaranteed to every citizen',
    color: 'from-blue-200 to-blue-300',
    icon: '📜',
    cqiReward: 70,
    badge: 'rights_defender',
    slides: [
      {
        type: 'intro',
        title: 'Welcome to Fundamental Rights',
        content: 'Human rights are rights we have simply because we exist as human beings. They are not granted by any state and apply to everyone regardless of nationality, religion, or ethnicity.',
        image: '🌍',
      },
      {
        type: 'content',
        title: 'Right to Equality',
        content: 'Every person is equal before the law and entitled to equal protection. This means no discrimination based on religion, race, caste, sex, or place of birth.',
        facts: [
          'Equality ensures fair treatment for all',
          'Prevents discrimination in public spaces',
          'Equal access to opportunities',
          'Protection against social injustice',
          'Equal rights regardless of background',
        ],
      },
      {
        type: 'content',
        title: 'Right to Freedom',
        content: 'Freedom of speech, expression, assembly, and movement are fundamental to a democratic society. These freedoms allow citizens to express themselves and participate in civic life.',
        facts: [
          'Freedom of speech and expression',
          'Freedom to assemble peacefully',
          'Freedom to form associations',
          'Freedom to move throughout the country',
          'Freedom to practice any profession',
        ],
      },
      {
        type: 'content',
        title: 'Right Against Exploitation',
        content: 'Citizens have the right to protection from forced labor, human trafficking, and child labor. The state is responsible for preventing exploitation of vulnerable groups.',
        facts: [
          'Prohibition of forced labor',
          'Prevention of human trafficking',
          'Child labor is strictly forbidden',
          'Protection of workers\' rights',
          'Minimum wages and safe working conditions',
        ],
      },
      {
        type: 'content',
        title: 'Right to Freedom of Religion',
        content: 'Every citizen has the right to profess, practice, and propagate any religion of their choice. The state remains secular and treats all religions equally.',
        facts: [
          'Freedom to practice any religion',
          'Right to propagate beliefs peacefully',
          'Freedom to manage religious affairs',
          'State protection for all faiths',
          'Secular governance and religious harmony',
        ],
      },
      {
        type: 'content',
        title: 'Right to Constitutional Remedies',
        content: 'If fundamental rights are violated, citizens can approach the courts for justice. The Constitution provides remedies to protect these rights from any violation.',
        facts: [
          'Right to appeal to courts',
          'Habeas corpus protection',
          'Protection from arbitrary detention',
          'Access to fair legal process',
          'Compensation for violations',
        ],
      },
      {
        type: 'content',
        title: 'How Rights Shape Society',
        content: 'Fundamental rights create a framework for a just society where everyone has equal dignity and opportunity. They protect minorities and vulnerable groups from tyranny and injustice.',
        facts: [
          'Rights protect individual dignity',
          'Ensure fair democratic participation',
          'Prevent abuse of government power',
          'Create accountability mechanisms',
          'Foster social harmony and justice',
        ],
      },
      {
        type: 'content',
        title: 'Responsibilities with Rights',
        content: 'Rights come with responsibilities. As we exercise our rights, we must respect the rights of others and not abuse them. This balance maintains social harmony.',
        facts: [
          'Exercise rights responsibly',
          'Respect rights of other citizens',
          'Obey laws and constitution',
          'Contribute to society positively',
          'Protect rights of vulnerable groups',
        ],
      },
      {
        type: 'final-quiz',
        title: 'Fundamental Rights Quiz',
        questions: [
          {
            question: 'Which of the following is NOT a fundamental right in most democracies?',
            options: [
              'Right to Equality before law',
              'Right to Freedom of speech',
              'Right to guaranteed wealth',
              'Right to Religious freedom',
            ],
            correct: 2,
            explanation: 'While governments should provide economic opportunities, guaranteed wealth is not a fundamental right. Rights protect freedoms and protections, not material guarantees.',
          },
          {
            question: 'What does the Right Against Exploitation primarily protect against?',
            options: [
              'Business failure',
              'Economic competition',
              'Forced labor and human trafficking',
              'Market price fluctuations',
            ],
            correct: 2,
            explanation: 'The Right Against Exploitation protects vulnerable people from forced labor, human trafficking, and child labor by imposing legal penalties on perpetrators.',
          },
          {
            question: 'Which right allows you to approach courts if your fundamental rights are violated?',
            options: [
              'Right to Equality',
              'Right to Constitutional Remedies',
              'Right to Freedom',
              'Right to Religion',
            ],
            correct: 1,
            explanation: 'The Right to Constitutional Remedies empowers citizens to seek legal redress through courts when any fundamental right is violated.',
          },
        ],
      },
    ],
  },
  {
    id: 'duties-citizens',
    title: 'Duties of Citizens',
    description: 'Learn about civic responsibilities and community engagement',
    color: 'from-green-200 to-green-300',
    icon: '🤝',
    cqiReward: 65,
    badge: 'civic_leader',
    slides: [
      {
        type: 'intro',
        title: 'Understanding Civic Duties',
        content: 'Rights come with responsibilities. As citizens, we have duties that help maintain a healthy, functioning society and build a stronger nation together.',
        image: '🏛️',
      },
      {
        type: 'content',
        title: 'Respect and Tolerance',
        content: 'We must respect the diversity of our nation and promote harmony across different communities. This creates a society where everyone feels valued and safe.',
        facts: [
          'Value our composite culture',
          'Respect different religions and beliefs',
          'Promote fraternity and unity',
          'Combat discrimination and prejudice',
          'Celebrate cultural diversity',
        ],
      },
      {
        type: 'content',
        title: 'Protecting Public Property',
        content: 'Public property belongs to everyone and should be protected and maintained. Damaging or vandalizing public assets hurts the entire community.',
        facts: [
          'Safeguard public buildings and facilities',
          'Maintain roads and infrastructure',
          'Protect parks and public spaces',
          'Report damage to authorities',
          'Take pride in shared resources',
        ],
      },
      {
        type: 'content',
        title: 'Environmental Protection',
        content: 'It is our duty to protect and improve the natural environment including forests, lakes, rivers, and wildlife. Environmental conservation ensures a sustainable future.',
        facts: [
          'Conserve natural resources',
          'Protect wildlife and forests',
          'Reduce pollution and waste',
          'Support renewable energy',
          'Practice sustainable living',
        ],
      },
      {
        type: 'content',
        title: 'Civic Participation and Voting',
        content: 'Citizens have the duty to participate in the democratic process. Voting is not just a right but a responsibility to choose leaders who will serve the nation.',
        facts: [
          'Participate in elections',
          'Vote responsibly and fairly',
          'Stay informed about issues',
          'Engage in civic discussions',
          'Support democratic institutions',
        ],
      },
      {
        type: 'content',
        title: 'Obey Laws and Constitution',
        content: 'Citizens must obey the laws of the land and respect the Constitution. This creates order and ensures that everyone lives safely and fairly.',
        facts: [
          'Respect constitutional authority',
          'Obey laws enacted by parliament',
          'Pay taxes honestly',
          'Follow traffic and safety rules',
          'Support law and order',
        ],
      },
      {
        type: 'content',
        title: 'Promoting Education and Health',
        content: 'Citizens should support education and public health initiatives. An educated and healthy society is stronger and more prosperous for everyone.',
        facts: [
          'Support public education',
          'Promote health awareness',
          'Encourage learning in communities',
          'Support vaccination programs',
          'Advocate for public health policies',
        ],
      },
      {
        type: 'content',
        title: 'National Defense and Service',
        content: 'Citizens may have duties related to national defense and safety. This includes respecting armed forces and supporting national security measures.',
        facts: [
          'Support national security',
          'Respect armed forces',
          'Contribute to defense efforts',
          'Report suspicious activities',
          'Maintain vigilance against threats',
        ],
      },
      {
        type: 'final-quiz',
        title: 'Duties of Citizens Quiz',
        questions: [
          {
            question: 'Which duty emphasizes protecting forests, rivers, and wildlife?',
            options: [
              'Civic Participation',
              'Environmental Protection',
              'Respecting Laws',
              'Educational Support',
            ],
            correct: 1,
            explanation: 'Environmental Protection is the duty to conserve natural resources and maintain ecological balance for future generations.',
          },
          {
            question: 'Why is voting considered a civic duty and not just a right?',
            options: [
              'It is mandatory by law',
              'It is a responsibility to choose leaders and shape democracy',
              'Only wealthy people vote',
              'It determines tax rates',
            ],
            correct: 1,
            explanation: 'Voting is a civic duty because participating in elections is essential for democracy to function and represents our responsibility to the nation.',
          },
          {
            question: 'What is the primary purpose of obeying laws?',
            options: [
              'To avoid punishment only',
              'To create order and ensure fair treatment for everyone',
              'To impress the government',
              'To maintain social inequality',
            ],
            correct: 1,
            explanation: 'Obeying laws creates social order and ensures that everyone is treated fairly and can live safely in society.',
          },
        ],
      },
    ],
  },
  {
    id: 'democracy-action',
    title: 'Democracy in Action',
    description: 'Understand how democracy works and your role in it',
    color: 'from-purple-200 to-purple-300',
    icon: '🗳️',
    cqiReward: 75,
    badge: 'democracy_guardian',
    slides: [
      {
        type: 'intro',
        title: 'The Power of Democracy',
        content: 'Democracy is government of the people, by the people, for the people. Your voice matters in shaping the nation through participation and voting.',
        image: '✊',
      },
      {
        type: 'content',
        title: 'Electoral Process and Voting',
        content: 'Free and fair elections are the cornerstone of democracy, allowing citizens to choose their representatives. Every vote counts equally regardless of background.',
        facts: [
          'Universal adult suffrage - everyone votes',
          'Secret ballot system for voter privacy',
          'Independent election commission oversight',
          'Regular elections ensure accountability',
          'Free and fair voting process',
        ],
      },
      {
        type: 'content',
        title: 'Checks and Balances',
        content: 'Democratic systems have three branches - Legislative, Executive, and Judicial - that balance each other. No single branch can become too powerful.',
        facts: [
          'Legislature makes and debates laws',
          'Executive implements and enforces policies',
          'Judiciary interprets laws fairly',
          'Each branch checks the others',
          'Power is distributed and limited',
        ],
      },
      {
        type: 'content',
        title: 'Rights and Freedoms in Democracy',
        content: 'Democracy protects fundamental rights including freedom of speech, press, and assembly. Citizens can voice opinions and criticize government peacefully.',
        facts: [
          'Freedom of speech and expression',
          'Freedom of press and media',
          'Right to peaceful protest',
          'Protection for political opposition',
          'Citizens can petition government',
        ],
      },
      {
        type: 'content',
        title: 'Parliament and Legislation',
        content: 'Parliament is the legislative body where elected representatives debate and create laws. Bills go through multiple readings and amendments before becoming law.',
        facts: [
          'Representatives debate issues openly',
          'Bills are discussed from multiple angles',
          'Citizens can petition parliament',
          'Laws must be transparent',
          'Parliamentary sessions are public',
        ],
      },
      {
        type: 'content',
        title: 'Judiciary and Rule of Law',
        content: 'The judiciary ensures that everyone is equal before the law. Courts protect rights and administer justice fairly without bias or favoritism.',
        facts: [
          'Independent court system',
          'Fair trials guaranteed',
          'Judges are impartial',
          'Legal appeals available',
          'Protection against injustice',
        ],
      },
      {
        type: 'content',
        title: 'Political Parties and Opposition',
        content: 'Multiple political parties represent different ideologies and interests. A strong opposition is essential for accountability and preventing authoritarian rule.',
        facts: [
          'Parties represent diverse views',
          'Opposition holds government accountable',
          'Peaceful transfer of power',
          'Competition of ideas',
          'Democratic debate and discussion',
        ],
      },
      {
        type: 'content',
        title: 'Local Democracy and Governance',
        content: 'Democracy works at local levels too through municipalities and village councils. Local governance brings decisions closer to the people.',
        facts: [
          'Local councils represent communities',
          'Municipal governments manage cities',
          'Direct participation in local issues',
          'Grassroots democratic participation',
          'Local accountability and transparency',
        ],
      },
      {
        type: 'final-quiz',
        title: 'Democracy in Action Quiz',
        questions: [
          {
            question: 'What principle ensures no single branch of government becomes too powerful?',
            options: [
              'Federalism',
              'Checks and Balances',
              'Secularism',
              'Socialism',
            ],
            correct: 1,
            explanation: 'Checks and Balances distribute power among three branches so each can limit the others, preventing concentration of authority.',
          },
          {
            question: 'Why is freedom of press important in a democracy?',
            options: [
              'So newspapers can publish anything',
              'To hold government accountable and inform citizens',
              'To make money from advertising',
              'To entertain people',
            ],
            correct: 1,
            explanation: 'Freedom of press is crucial so media can investigate government actions, expose corruption, and keep citizens informed about important issues.',
          },
          {
            question: 'What role does opposition play in democratic government?',
            options: [
              'To prevent any progress',
              'To create chaos',
              'To hold government accountable and prevent authoritarianism',
              'To support all government decisions',
            ],
            correct: 2,
            explanation: 'Opposition parties are essential for accountability, offering alternative policies and preventing any single party from gaining unchecked power.',
          },
        ],
      },
    ],
  },
  {
    id: 'environmental-awareness',
    title: 'Environmental Awareness',
    description: 'Become a guardian of our planet and sustainable future',
    color: 'from-emerald-200 to-teal-300',
    icon: '🌱',
    cqiReward: 60,
    badge: 'green_citizen',
    slides: [
      {
        type: 'intro',
        title: 'Our Environmental Responsibility',
        content: 'The Earth is our shared home. Understanding environmental issues is the first step toward sustainable living and protecting nature for future generations.',
        image: '🌏',
      },
      {
        type: 'content',
        title: 'Climate Change and Global Warming',
        content: 'Climate change affects everyone through extreme weather, rising sea levels, and ecosystem disruption. Reducing greenhouse gases is critical for our future.',
        facts: [
          'Global temperatures are rising',
          'Extreme weather events increasing',
          'Sea levels rising from melting ice',
          'Reducing carbon footprint is essential',
          'Renewable energy is the solution',
        ],
      },
      {
        type: 'content',
        title: 'Pollution and Air Quality',
        content: 'Air pollution from vehicles, factories, and burning fuels harms human health and the environment. Clean air is essential for all living things.',
        facts: [
          'Vehicle emissions are major pollutants',
          'Industrial pollution affects water and air',
          'Burning fossil fuels releases CO2',
          'Air quality impacts respiratory health',
          'Clean energy reduces pollution',
        ],
      },
      {
        type: 'content',
        title: 'Water Conservation and Protection',
        content: 'Fresh water is a precious resource. Many communities face water scarcity. We must conserve water and prevent pollution of rivers, lakes, and groundwater.',
        facts: [
          'Only 3% of water is fresh',
          'Millions lack access to clean water',
          'Agricultural practices waste water',
          'Industrial pollution contaminates water',
          'Individual conservation matters greatly',
        ],
      },
      {
        type: 'content',
        title: 'Biodiversity and Ecosystem Protection',
        content: 'Plants and animals depend on healthy ecosystems. Deforestation, habitat loss, and poaching threaten biodiversity essential for life on Earth.',
        facts: [
          'Forests provide oxygen and carbon storage',
          'Wildlife habitats are disappearing',
          'Species extinction rates are accelerating',
          'Ecosystems provide food and medicine',
          'Protected areas preserve biodiversity',
        ],
      },
      {
        type: 'content',
        title: 'Waste Management and Recycling',
        content: 'Proper waste management prevents pollution and conserves resources. Recycling, composting, and reducing consumption are practical solutions.',
        facts: [
          'Reduce consumption at the source',
          'Reuse items instead of discarding',
          'Recycle plastics, metals, and paper',
          'Compost organic waste',
          'Avoid single-use plastics',
        ],
      },
      {
        type: 'content',
        title: 'Sustainable Living and Green Choices',
        content: 'Individual actions compound into global impact. Sustainable choices like using renewable energy, buying local, and reducing waste help the planet.',
        facts: [
          'Use public transport and carpool',
          'Support renewable energy sources',
          'Buy local and seasonal products',
          'Reduce energy consumption',
          'Support sustainable businesses',
        ],
      },
      {
        type: 'content',
        title: 'Environmental Justice and Rights',
        content: 'Every community has the right to a clean environment. Environmental protection must be equitable, protecting vulnerable communities from pollution.',
        facts: [
          'Low-income areas face pollution',
          'Indigenous lands need protection',
          'Environmental justice is crucial',
          'All communities deserve clean air/water',
          'Rights-based environmental protection',
        ],
      },
      {
        type: 'final-quiz',
        title: 'Environmental Awareness Quiz',
        questions: [
          {
            question: 'What is the most effective way to reduce climate change?',
            options: [
              'Using electric vehicles only',
              'Reducing overall greenhouse gas emissions',
              'Planting trees alone',
              'Recycling everything',
            ],
            correct: 1,
            explanation: 'While all actions help, the most effective approach is systematically reducing greenhouse gas emissions across energy, transport, and industry.',
          },
          {
            question: 'Why is water conservation important for environmental protection?',
            options: [
              'It saves money on water bills',
              'Fresh water is limited and pollution-vulnerable',
              'It increases water prices',
              'Only in desert regions',
            ],
            correct: 1,
            explanation: 'Only 3% of water is fresh, making it a precious resource. Conservation protects this limited supply for all living things.',
          },
          {
            question: 'What role does biodiversity play in ecosystems?',
            options: [
              'It has no practical importance',
              'Provides food, medicine, and ecosystem stability',
              'Only matters for nature lovers',
              'Complicates environmental management',
            ],
            correct: 1,
            explanation: 'Biodiversity is essential - it stabilizes ecosystems, provides food and medicine, and ensures resilience against environmental changes.',
          },
        ],
      },
    ],
  },
];

export const getModuleById = (id) => MODULES.find(m => m.id === id);
